### PR TITLE
Bug fixes + Adding Material Design

### PR DESCRIPTION
**Pull request by alonheller**
Bug fix: meetup icon link fixed
Bug fix: mailto: email fixed
Bug fix: Footer classes are missing from scss file
New feature: Material Design added
New feature: "Submit your papers" link open in new window, and has tooltip
Misc: Angular added (ng-conf site without Angular in it, is this a joke?)
Misc: Style fixed

### CODE REVIEW

**Comment by alonheller** [comment]
Uri,
You need also merging the changes of the second commit.

**Comment by urish** [comment]
Done, thanks a millon!

**Comment by kaminskypavel** [comment]
$scope.hachanaLeMazgan = '';

@allonheller - nice one.

**Comment by urish** [comment]
+1

**Comment by kaminskypavel** [comment]
מישהו מגיע?

---------- Forwarded message ---------
From: Amazon Web Services <aws-marketing-email-replies@amazon.com>
Date: Tue, May 19, 2015 at 8:06 AM
Subject: Register now for the AWS Summit Tel Aviv 2015
To: <kaminsky.pavel@gmail.com>


                   [image: Amazon Web Services Summit Series 2015]
<http://mkto-sj010128.com/dc/ajD_BapU74vzOhWVQvr7p-iQMyFpurP1psnMfszj4wBvGXR-ncTIZUt_Mx7oJy9WjZWD1LCQd_Unit5bGZ8oXW9rVES8W4t7_MvcHBQhGXg4qwM_HXwTwAPhb7YbFhdpm7JkyAsXk-88O6M1X47AeYMRBdlTAmWrVqhcl0XED-mcffNg5o8p8y2FEEEYdw6WpV_X8cxdUVa4rTk6MBG0SSLTefIZCY5js_AYuh0T1C0xV-DrQk7vCu8GUaGABTQw/WK0rZyVc30H3AKM0000Pr00>
               AWS Summit
TEL AVIV

*June 25, 2015 | Tel Aviv Convention Center*



AWS Summit Tel Aviv 2015 is now open for registration! Join AWS and a
broad range of organizations at this year's AWS Summit.


Register Now →
<http://mkto-sj010128.com/dc/ajD_BapU74vzOhWVQvr7p-iQMyFpurP1psnMfszj4wDSvvFg-WV0I6v-6Cebc-vybm_DPzqG3k4huUq-GndvjkN0eZK8DRbKwtvXl1fMu80GvHLrkPh3uIuwwqGOrVHqR6muEDgOf-2RNWDWv3UPBvK8PIZhU4s3SMZ32pwfn5rWWz95uo_N2Xtric9F74v7Qml3ANwpjwbEOPolREtGspUQdonobnuv-VyF5pQYDqvDIEElu-7Vv1GwY6yuZKjEafiGEPwJdFOPLG5rzegvBQ==/WK0rZyVc30H3AKM0000Pr00>

Learn more »
<http://mkto-sj010128.com/dc/ajD_BapU74vzOhWVQvr7p-iQMyFpurP1psnMfszj4wBvGXR-ncTIZUt_Mx7oJy9WjZWD1LCQd_Unit5bGZ8oXW9rVES8W4t7_MvcHBQhGXg4qwM_HXwTwAPhb7YbFhdpm7JkyAsXk-88O6M1X47AeYMRBdlTAmWrVqhcl0XED-mcffNg5o8p8y2FEEEYdw6WpV_X8cxdUVa4rTk6MBG0SSLTefIZCY5js_AYuh0T1C0xV-DrQk7vCu8GUaGABTQw/WK0rZyVc30H3AKM0000Pr00>


   Find out what else is happening at the Summit           * [image: Meet a
Solutions Architecht]
<http://mkto-sj010128.com/dc/ajD_BapU74vzOhWVQvr7p-iQMyFpurP1psnMfszj4wDCbxhFEjeHHeBch10xKbQDBIuTCDqCtNZs_tNfbmtVi1r9tHmokCqhc6Rl-BnRc3M2ES6GWVQFcez9pxqXFun6cQkjQSaYSgXer16HCSzD1JtMnx3A1M7Ce6cYzyIP4PJMcnSnWDT6sUnTV2SLrc8RQtIfTWl7RHHAUnxf2l0PcJUojHsgfnXu_HwsQhbhzRAtxdyua-FK-MSYrYoR5xyLAPjgDG6JpdPpWvmsB7_ZfA==/WK0rZyVc30H3AKM0000Pr00>*
 [image: Hands-on Labs]
<http://mkto-sj010128.com/dc/ajD_BapU74vzOhWVQvr7p-iQMyFpurP1psnMfszj4wAlXen2M1Knm8ep4su2i18aACfl_zTk5u9mCYKARMFBfbER62n6-_gpEyawzOmLyye0X9CPyI8kKhttSQT0PT3WXXM9HuNfZcgjXM5qJvjmg_YyMpnTQidESFWkyZQOqV2ZZIKiNlHCmJhlNujwLA29XeGtYXyUz4_B1E4qq4XOsVDjALEtD_mrBeIxQxtY3O3gy8-L05jEonl0wpPhK3rXLPa1w3tSTnMcMu5KH_6dzg==/WK0rZyVc30H3AKM0000Pr00>

*Meet a Solutions Architect*

Are you considering AWS but have burning questions? Take advantage of this
event to have a 1:1 meeting with one of our AWS solutions architects and
experts.

Learn more »
<http://mkto-sj010128.com/dc/ajD_BapU74vzOhWVQvr7p-iQMyFpurP1psnMfszj4wDCbxhFEjeHHeBch10xKbQDBIuTCDqCtNZs_tNfbmtVi1r9tHmokCqhc6Rl-BnRc3M2ES6GWVQFcez9pxqXFun6cQkjQSaYSgXer16HCSzD1JtMnx3A1M7Ce6cYzyIP4PJMcnSnWDT6sUnTV2SLrc8RQtIfTWl7RHHAUnxf2l0PcJUojHsgfnXu_HwsQhbhzRAtxdyua-FK-MSYrYoR5xyLAPjgDG6JpdPpWvmsB7_ZfA==/WK0rZyVc30H3AKM0000Pr00>

*Hands-on Labs*

These self-paced labs will help you learn how use AWS services and gain
confidence with the platform using step-by-step instructions to complete a
pre-designed scenario.

Learn more »
<http://mkto-sj010128.com/dc/ajD_BapU74vzOhWVQvr7p-iQMyFpurP1psnMfszj4wAlXen2M1Knm8ep4su2i18aACfl_zTk5u9mCYKARMFBfbER62n6-_gpEyawzOmLyye0X9CPyI8kKhttSQT0PT3WXXM9HuNfZcgjXM5qJvjmg_YyMpnTQidESFWkyZQOqV2ZZIKiNlHCmJhlNujwLA29XeGtYXyUz4_B1E4qq4XOsVDjALEtD_mrBeIxQxtY3O3gy8-L05jEonl0wpPhK3rXLPa1w3tSTnMcMu5KH_6dzg==/WK0rZyVc30H3AKM0000Pr00>

Featured Sponsor
                       [image: Intel]
<http://mkto-sj010128.com/dc/ajD_BapU74vzOhWVQvr7pyCLK7YhR1Xz2yakxCZlH-yHLYmr5Pi5rohiIi0Txz8mZau_uPFNZiTNcK_yZbNDGqmmVu10tkcrFZxRtg3ATD99ftdJcmEnn74Bu5PxyPeIubBLoRK_Hsygvd6tKGYTtVT00XrfuUoUmKEudqOFtCB88OPbGRLPXGGvnw7EA68ia0sxJi6D-8stW_DgWneN-mlpJZ-MWs1iSlJ2q5ywLtU=/WK0rZyVc30H3AKM0000Pr00>

Intel <http://mkto-sj010128.com/ey0PIA03000VKr00cr03M0K> and AWS share a
passion for delivering constant innovation and value. The latest Intel®
Xeon® processors are utilized by AWS. Come and meet Intel to learn about
the partnership, High Performance Computing Software Lustre and our end to
end Internet of Things platform.

[image: Sincerely, Amazon Web Services]
<http://mkto-sj010128.com/dc/ajD_BapU74vzOhWVQvr7p5bxCQ4zGVm1ZdT2xKYveJZga2BCHB7UIvhOi6VHUo2bFgTy34703Gr1zAJFJdYg8xWTKiVdyH9vVvYbxyPDJMpDvGJCln6Ti1WS01m1fc96GF8K-W2fnHuu1EL1g5zycQ==/WK0rZyVc30H3AKM0000Pr00>
               [image: awsblog-icon]
<http://mkto-sj010128.com/dc/ajD_BapU74vzOhWVQvr7p0486BTljVMiJxb-dUE36FaqzDqs0uSBX4efRg1x-qU7-2JPzLM2FvdoPYGWXJ7j4RVFtov78a-FA6xtgqlgOS_CUTWj3nswnbYciyKR7ooTJ7Et2itHE8rOsTIt73OB0CGET6lecBvMtUNjzwdogwCLeX3hyzyRbpF2YkVt6rt7/WK0rZyVc30H3AKM0000Pr00>
  [image: fb] <http://mkto-sj010128.com/U01M0cA03V0KKr03ry000JP>
  [image: tw] <http://mkto-sj010128.com/o03Ky002r00rMK0cPAVK030>
  [image: tw] <http://mkto-sj010128.com/K000cKV003rL33KPM0ry0A0>
  [image: tw]

We hope you enjoyed receiving this message. If you'd rather not receive
future emails from Amazon Web Services, unsubscribe here
<http://mkto-sj010128.com/u/GrV0Ar30P4cMK0K30000My0>.

Amazon Web Services, Inc. is a subsidiary of Amazon.com, Inc. Amazon.com is
a registered trademark of Amazon.com, Inc. This message produced and
distributed by Amazon Web Services, Inc., 410 Terry Ave. North, Seattle, WA
98109-5210.

©2015, Amazon Web Services, Inc. or its affiliates. All rights reserved.
View our privacy policy
<http://mkto-sj010128.com/dcu/ajD_BapU74vzOhWVQvr7p2gvewIU_49R6VB0mTGKdZUoHdiwG_Sqmwh71jddJ3dN2WDSJH4RDZ9yyNxPQeVzgCvwrkhlvXPq0Ym23PJhp8iuoqMisG4gvBUv3Y-g26QrmJhkzM9FiQtJp4SBt47Vhg==/WK0rZyVc30H3AKM0000Pr00>.

**Pull request merged**
